#!/bin/sh
# language relation
#    $Id: gen_data.sh,v 1.1 2005/03/01 11:17:36 lav Exp $

OUTFILE=language_data.h

cat <<EOF >$OUTFILE
/* Do not edit this file!
   It is autogenerated with LIBNATSPEC
*/
static const struct language_entry language_relation[] =
{
	/* TeX name   Babel name  GUI name  isocode */
EOF
cat <<EOF >>$OUTFILE

};
EOF
