#!/bin/sh
# charset relation generator
OUTFILE=get_charset_data.h

print()
{
	printf "\t{ \"%s\",\t%d,\t\"%s\",\t\"%s\",\t\"%s\",\t\"%s\" }" $@ >>$OUTFILE
}

echo Test string:
./print_data_string || exit 1
echo
cat <<EOF >$OUTFILE
/* Do not edit this file!
   It is autogenerated from WINE program print_data_string.c
*/
static const struct charsetrel_entry charset_relation[] =
{
	/* unix locale,       lcid,    unix,       windows,    dos,      mac charset */
EOF
for i in `locale -a | sort`
do
#	printf "\t{ %-15s %d,\t\"%s\",\t\"%s\",\t\"%s\",\t\"%s\" }" "\"$i\"," `LANG=$i ./print_data_string 2>/dev/null` >>$OUTFILE
	print $i `LANG=$i ./print_data_string 2>/dev/null`
	echo -e "," >>$OUTFILE
done
echo >>$OUTFILE
echo "/* Follow entries is dummy for ASCII/ANSI encoding */" >>$OUTFILE
print "POSIX" 1033 ASCII CP1252 IBM437 ""
echo -e "," >>$OUTFILE
print "POSIX" 1033 ANSIX341968 CP1252 IBM437 ""
echo >>$OUTFILE
cat <<EOF >>$OUTFILE

};
EOF
